// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriGuide.Models;

#nullable disable

namespace NutriGuide.Migrations
{
    [DbContext(typeof(NutriGuideDbContext))]
    [Migration("20251217130143_createDB")]
    partial class createDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FavoriteMeal", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<int>("MealId")
                        .HasColumnType("int")
                        .HasColumnName("MealID");

                    b.HasKey("CustomerId", "MealId")
                        .HasName("FavoriteMeal_PK");

                    b.HasIndex("MealId");

                    b.ToTable("FavoriteMeal", (string)null);
                });

            modelBuilder.Entity("NutriGuide.Models.AvoidFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("AvoidFoodsID_PK");

                    b.HasIndex("CustomerId");

                    b.ToTable("AvoidFoods");
                });

            modelBuilder.Entity("NutriGuide.Models.ChronicDisease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("ChronicDiseasesID_PK");

                    b.HasIndex("CustomerId");

                    b.ToTable("ChronicDiseases");
                });

            modelBuilder.Entity("NutriGuide.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<decimal>("ActivityLevel")
                        .HasColumnType("decimal(5, 3)");

                    b.Property<int?>("Age")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(datediff(year,[BirthDate],getdate()))", false);

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Bmi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("BMI")
                        .HasComputedColumnSql("(CONVERT([decimal](5,2),[Weight]/power([Height]/(100.0),(2))))", false);

                    b.Property<decimal?>("Bmr")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(7, 2)")
                        .HasColumnName("BMR")
                        .HasComputedColumnSql("(CONVERT([decimal](7,2),case when [Gender]='Male' then (((10)*[Weight]+(6.25)*[Height])-(5)*datediff(year,[BirthDate],getdate()))+(5) when [Gender]='Female' then (((10)*[Weight]+(6.25)*[Height])-(5)*datediff(year,[BirthDate],getdate()))-(161)  end))", false);

                    b.Property<decimal?>("Calories")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(7, 2)")
                        .HasComputedColumnSql("(CONVERT([decimal](7,2),case when [Gender]='Male' then ((((10)*[Weight]+(6.25)*[Height])-(5)*datediff(year,[BirthDate],getdate()))+(5))*[ActivityLevel] when [Gender]='Female' then ((((10)*[Weight]+(6.25)*[Height])-(5)*datediff(year,[BirthDate],getdate()))-(161))*[ActivityLevel]  end))", false);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("IdealWeight")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(5, 2)")
                        .HasComputedColumnSql("(CONVERT([decimal](5,2),case when [Gender]='Male' then (48)+(2.7)*(([Height]-(152))/(2.54)) when [Gender]='Female' then (45.5)+(2.2)*(([Height]-(152))/(2.54))  end))", false);

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id")
                        .HasName("CustomerID_PK");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("NutriGuide.Models.DailyWieght", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<DateOnly?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id")
                        .HasName("DailyWieghtID_PK");

                    b.HasIndex("CustomerId");

                    b.ToTable("DailyWieght", (string)null);
                });

            modelBuilder.Entity("NutriGuide.Models.GoalPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("GoalPlanID_PK");

                    b.ToTable("GoalPlan", (string)null);
                });

            modelBuilder.Entity("NutriGuide.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Ingredie__3214EC2760389CD1");

                    b.ToTable("Ingredient", (string)null);
                });

            modelBuilder.Entity("NutriGuide.Models.IngredientMeal", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("int")
                        .HasColumnName("MealID");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("MealId", "IngredientId")
                        .HasName("IngredientMeal_PK");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientMeal", (string)null);
                });

            modelBuilder.Entity("NutriGuide.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Calories")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Carbs")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Fat")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("HealthBenefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealTime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MealType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.Property<string>("Preparation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Protein")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("MealID_PK");

                    b.HasIndex("PlanId");

                    b.ToTable("Meal", (string)null);
                });

            modelBuilder.Entity("NutriGuide.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("MedicinesID_PK");

                    b.HasIndex("CustomerId");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("NutriGuide.Models.MedicineTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<TimeOnly>("TakeTime")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__Medicine__3214EC2730893B60");

                    b.HasIndex("MedicineId");

                    b.ToTable("MedicineTimes");
                });

            modelBuilder.Entity("NutriGuide.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScheduleTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("NotificationID_PK");

                    b.HasIndex("CustomerId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("NutriGuide.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<decimal?>("DailyCalories")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("GoalId")
                        .HasColumnType("int")
                        .HasColumnName("GoalID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfMeals")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("SystemTypeId")
                        .HasColumnType("int")
                        .HasColumnName("SystemTypeID");

                    b.HasKey("Id")
                        .HasName("PlanID_PK");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GoalId");

                    b.HasIndex("SystemTypeId");

                    b.ToTable("Plan", (string)null);
                });

            modelBuilder.Entity("NutriGuide.Models.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GeneratedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.HasKey("Id")
                        .HasName("ShoppingListID_PK");

                    b.HasIndex("PlanId");

                    b.ToTable("ShoppingList", (string)null);
                });

            modelBuilder.Entity("NutriGuide.Models.ShoppingListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.Property<bool?>("IsBought")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ListId")
                        .HasColumnType("int")
                        .HasColumnName("ListID");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("ShoppingListItems_PK");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ListId");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("NutriGuide.Models.SystemTypePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("SystemTypePlan_PK");

                    b.ToTable("SystemTypePlan", (string)null);
                });

            modelBuilder.Entity("NutriGuide.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("ResetAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ResetPasswordCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ResetPasswordExpiry")
                        .HasColumnType("datetime");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("VerificationCodeExpiry")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("Users_PK");

                    b.HasIndex(new[] { "Email" }, "unique_EmailUser")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FavoriteMeal", b =>
                {
                    b.HasOne("NutriGuide.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("CustomerFavorite_FK");

                    b.HasOne("NutriGuide.Models.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .IsRequired()
                        .HasConstraintName("FavoriteMeal_FK");
                });

            modelBuilder.Entity("NutriGuide.Models.AvoidFood", b =>
                {
                    b.HasOne("NutriGuide.Models.Customer", "Customer")
                        .WithMany("AvoidFoods")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("CustomerAvoidFoodsID_FK");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NutriGuide.Models.ChronicDisease", b =>
                {
                    b.HasOne("NutriGuide.Models.Customer", "Customer")
                        .WithMany("ChronicDiseases")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("DiseasesCustomerID_FK");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NutriGuide.Models.Customer", b =>
                {
                    b.HasOne("NutriGuide.Models.User", "IdNavigation")
                        .WithOne("Customer")
                        .HasForeignKey("NutriGuide.Models.Customer", "Id")
                        .IsRequired()
                        .HasConstraintName("CustomerID_FK");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("NutriGuide.Models.DailyWieght", b =>
                {
                    b.HasOne("NutriGuide.Models.Customer", "Customer")
                        .WithMany("DailyWieghts")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("CustomerDailyCalories_FK");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NutriGuide.Models.IngredientMeal", b =>
                {
                    b.HasOne("NutriGuide.Models.Ingredient", "Ingredient")
                        .WithMany("IngredientMeals")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("IngredientFoodID_FK");

                    b.HasOne("NutriGuide.Models.Meal", "Meal")
                        .WithMany("IngredientMeals")
                        .HasForeignKey("MealId")
                        .IsRequired()
                        .HasConstraintName("MealFoodID_FK");

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("NutriGuide.Models.Meal", b =>
                {
                    b.HasOne("NutriGuide.Models.Plan", "Plan")
                        .WithMany("Meals")
                        .HasForeignKey("PlanId")
                        .HasConstraintName("MealPlanID_FK");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("NutriGuide.Models.Medicine", b =>
                {
                    b.HasOne("NutriGuide.Models.Customer", "Customer")
                        .WithMany("Medicines")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("MedicinesCustomerID_FK");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NutriGuide.Models.MedicineTime", b =>
                {
                    b.HasOne("NutriGuide.Models.Medicine", "Medicine")
                        .WithMany("MedicineTimes")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK_MedicineTimes_Medicine");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("NutriGuide.Models.Notification", b =>
                {
                    b.HasOne("NutriGuide.Models.Customer", "Customer")
                        .WithMany("Notifications")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("CustomerNotificationID_FK");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NutriGuide.Models.Plan", b =>
                {
                    b.HasOne("NutriGuide.Models.Customer", "Customer")
                        .WithMany("Plans")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("CustomerPlanID_FK");

                    b.HasOne("NutriGuide.Models.GoalPlan", "Goal")
                        .WithMany("Plans")
                        .HasForeignKey("GoalId")
                        .IsRequired()
                        .HasConstraintName("GoalPlanID_FK");

                    b.HasOne("NutriGuide.Models.SystemTypePlan", "SystemType")
                        .WithMany("Plans")
                        .HasForeignKey("SystemTypeId")
                        .IsRequired()
                        .HasConstraintName("SystemTypeID_FK");

                    b.Navigation("Customer");

                    b.Navigation("Goal");

                    b.Navigation("SystemType");
                });

            modelBuilder.Entity("NutriGuide.Models.ShoppingList", b =>
                {
                    b.HasOne("NutriGuide.Models.Plan", "Plan")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("PlanId")
                        .HasConstraintName("PlanShoppingList_FK");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("NutriGuide.Models.ShoppingListItem", b =>
                {
                    b.HasOne("NutriGuide.Models.Ingredient", "Ingredient")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("IngredientId")
                        .HasConstraintName("IngredientItemID_FK");

                    b.HasOne("NutriGuide.Models.ShoppingList", "List")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("ListId")
                        .HasConstraintName("ListItemsID_FK");

                    b.Navigation("Ingredient");

                    b.Navigation("List");
                });

            modelBuilder.Entity("NutriGuide.Models.Customer", b =>
                {
                    b.Navigation("AvoidFoods");

                    b.Navigation("ChronicDiseases");

                    b.Navigation("DailyWieghts");

                    b.Navigation("Medicines");

                    b.Navigation("Notifications");

                    b.Navigation("Plans");
                });

            modelBuilder.Entity("NutriGuide.Models.GoalPlan", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("NutriGuide.Models.Ingredient", b =>
                {
                    b.Navigation("IngredientMeals");

                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("NutriGuide.Models.Meal", b =>
                {
                    b.Navigation("IngredientMeals");
                });

            modelBuilder.Entity("NutriGuide.Models.Medicine", b =>
                {
                    b.Navigation("MedicineTimes");
                });

            modelBuilder.Entity("NutriGuide.Models.Plan", b =>
                {
                    b.Navigation("Meals");

                    b.Navigation("ShoppingLists");
                });

            modelBuilder.Entity("NutriGuide.Models.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("NutriGuide.Models.SystemTypePlan", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("NutriGuide.Models.User", b =>
                {
                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
